# GAME_USER table

# --- !Ups

CREATE TABLE IF NOT EXISTS GAME_USER(
  `ID` int(11) UNSIGNED PRIMARY KEY NOT NULL,
  `PASSWORD` varchar(64) NOT NULL,
  `USERNAME` varchar(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# --- !Downs
