# add scores to GAME table

# --- !Ups

ALTER TABLE `ROUND`
MODIFY `CATEGORY_ID` BIGINT(20) NULL,
MODIFY `QUES_ONE` BIGINT(20) NULL,
MODIFY `QUES_TWO` BIGINT(20) NULL,
MODIFY `QUES_THREE` BIGINT(20) NULL;

# --- !Downs

